# src/recomind/data_embedding/core/pipeline.py

"""
Main ingestion pipeline orchestrating all steps
"""
from core.database_scanner import DatabaseScanner
from core.services.description_generator import DescriptionGenerator
from core.repositories.vector_repository import VectorRepository
from core.teams.manager import TeamAssignmentManager
from clients import database_client
from clients import teams_client 


def run_ingestion_pipeline(company_id: str):
    """
    Orchestrates the entire ingestion process from data scanning to vector saving,
    including team assignment.
    
    Args:
        company_id: The company UUID to process
    """
    print("=" * 70)
    print("--- Starting Complete Ingestion Pipeline ---")
    print(f"Company ID: {company_id}")
    print("=" * 70)
    
    # ========================================================================
    # PHASE 1: DATABASE SCHEMA EMBEDDING (Existing Pipeline)
    # ========================================================================
    
    # Step 1: Fetch database connection settings
    print("\n[Step 1/7] Fetching database connection settings...")
    source_settings = database_client.fetch_source_db_settings(company_id)

    if not source_settings:
        print("Pipeline aborted: Failed to fetch database connection settings.")
        return
    
    # Step 2: Save the fetched settings for auditing
    print("\n[Step 2/7] Saving connection settings for audit...")
    database_client.save_settings_to_db(source_settings)
    print(f"✓ Company ID {source_settings['company_id']} settings loaded.")
    
    # Step 3: Scan tables
    print("\n[Step 3/7] Scanning database schema...")
    scanner = DatabaseScanner(db_settings=source_settings)
    tables_data = scanner.scan_tables()

    if not tables_data:
        print("Pipeline aborted: No table data was found by the scanner.")
        return
    print(f"✓ Found {len(tables_data)} tables to process.")

    # Step 4: Generate descriptions using LLM
    print("\n[Step 4/7] Generating table descriptions using LLM...")
    generator = DescriptionGenerator()
    data_with_descriptions = generator.generate_for_tables(tables_data, source_settings)

    if not data_with_descriptions:
        print("Pipeline aborted: No descriptions were generated by the LLM.")
        return
    print(f"✓ Generated descriptions for {len(data_with_descriptions)} tables.")

    # Step 5: Save vectors to the vector store
    print("\n[Step 5/7] Creating embeddings and saving to vector database...")
    vector_repo = VectorRepository()
    vector_repo.save_embeddings(data_with_descriptions)
    print("✓ Table embeddings saved successfully.")

    # ========================================================================
    # PHASE 2: TEAM ASSIGNMENT (New Feature)
    # ========================================================================
    
    try:
        # Step 6: Fetch teams from API
        print("\n[Step 6/7] Fetching teams for company...")
        teams_list = teams_client.fetch_company_teams(company_id)
        
        if not teams_list:
            print("⚠ No teams found for this company. Skipping team assignment.")
            print("\n--- Ingestion Pipeline Completed (without team assignment)! ---")
            return
        
        print(f"✓ Found {len(teams_list)} teams: {teams_list}")
        
        # Step 7: Run team assignment
        print("\n[Step 7/7] Running team assignment process...")
        
        # Get table embeddings from database
        table_embeddings = vector_repo.get_table_embeddings(company_id)
        
        # Initialize team assignment manager
        team_manager = TeamAssignmentManager()
        
        # Run the assignment pipeline
        assignments, confidence_scores = team_manager.run_assignment_pipeline(
            company_id=company_id,
            teams_list=teams_list,
            tables_with_embeddings=table_embeddings,
            threshold=0.6  # Similarity threshold for team assignment
        )
        
        # Update the database with team assignments
        vector_repo.update_team_assignments(
            company_id=company_id,
            table_assignments=assignments,
            confidence_scores=confidence_scores
        )
        
        print("✓ Team assignment completed successfully!")
        
    except Exception as e:
        print(f"\n⚠ Warning: Team assignment failed: {e}")
        print("Pipeline will continue, but team_name column will remain empty.")
        import traceback
        traceback.print_exc()

    # ========================================================================
    print("\n" + "=" * 70)
    print("✓✓✓ Complete Ingestion Pipeline Finished Successfully! ✓✓✓")
    print("=" * 70)


if __name__ == "__main__":
    # For testing - replace with actual company_id
    test_company_id = "fb140d33-7e96-474d-a06d-ab3a6c65d1a9"
    run_ingestion_pipeline(test_company_id)