"""GraphState definition for LangGraph pipeline."""

from typing import TypedDict, Optional, List, Dict, Any
import pandas as pd


class GraphState(TypedDict):
    """
    Represents the internal state of the LangGraph data analysis pipeline.

    Attributes:
        user_request: The original natural language request from the user.
        data_type: Identified category of data ('employees', 'sales', etc.).
        dataframe: The pandas DataFrame being cleaned and analyzed.
        cleaning_plan: List of cleaning actions generated by the LLM.
        kpi_plan: List of KPI calculation instructions generated by the LLM.
        kpis: Dictionary containing calculated KPI metrics.
        analysis_report: The final markdown report string generated for the user.
    """

    user_request: Optional[str]
    data_type: Optional[str]
    dataframe: Optional[pd.DataFrame]
    cleaning_plan: Optional[List[Dict[str, Any]]]
    kpi_plan: Optional[List[Dict[str, Any]]]
    kpis: Optional[Dict[str, Any]]
    analysis_report: Optional[str]
